# Generated by Django 2.2 on 2021-04-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(max_length=255),
        ),
    ]
