# Generated by Django 2.2 on 2021-04-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_auto_20210401_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(upload_to='C:\\Users\\ANKITMISHRA\\Desktop\\lco-tubers\\tubers\\static\\assets\\images'),
        ),
    ]
